const OurProducts = [
   {
      id: 1,
      name: "TAGAS Printed Hoodies",
      price: 599,
      oldPrice: 1499,
      discount: "-60%",
      rating: 4.7,
      reviewsCount: 235,
      image: "https://m.media-amazon.com/images/I/61JgIelmvSL._SY741_.jpg",
   },
   {
      id: 2,
      name: "ASIAN Women's Running Shoes",
      price: 599,
      oldPrice: 799,
      discount: "-25%",
      rating: 4.8,
      reviewsCount: 180,
      image: "https://m.media-amazon.com/images/I/61vRXtZcy7L._SY625_.jpg",
   },
   {
      id: 3,
      name: "Ladies Purse Handbag",
      price: 899,
      oldPrice: 3599,
      discount: "-67%",
      rating: 4.8,
      reviewsCount: 1200,
      image: "https://m.media-amazon.com/images/I/71snBOUnNGS._SY625_.jpg",
   },
   {
      id: 4,
      name: "FCUK Analog Blue Dial",
      price: 1093,
      oldPrice: 4750,
      discount: "-77%",
      rating: 4.6,
      reviewsCount: 320,
      image: "https://m.media-amazon.com/images/I/61MG7QNKHgL._SY679_.jpg",
   },
   {
      id: 5,
      name: "Lymio Men Tshirt",
      price: 799,
      oldPrice: 2999,
      discount: "-87%",
      rating: 4.7,
      reviewsCount: 150,
      image: "https://m.media-amazon.com/images/I/71x4rLhMkML._SY741_.jpg",
   },
   {
      id: 6,
      name: "Study Table for students",
      price: 598,
      oldPrice: 999,
      discount: "-40%",
      rating: 4.5,
      reviewsCount: 90,
      image: "https://m.media-amazon.com/images/I/41QGdc77iBL._SX300_SY300_QL70_FMwebp_.jpg",
   },
];

export default OurProducts;
