const reduxConstants = {
   // SIGNUP
   SIGNUP_LOAD: "SIGNUP_LOAD",
   SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
   SIGNUP_FAIL: "SIGNUP_FAIL",
   // LOGIN
   LOGIN_LOAD: "LOGIN_LOAD",
   LOGIN_SUCCESS: "LOGIN_SUCCESS",
   LOGIN_FAIL: "LOGIN_FAIL",
   // CREATE PRODUCT
   CREATE_PRODUCT_LOAD: "CREATE_PRODUCT_LOAD",
   CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
   CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",
   //GET PRODUCT
   GET_PRODUCT_LOAD: "GET_PRODUCT_LOAD",
   GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
   GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",
   //GET PRODUCT CATEGORY
   GET_PRODUCT_CATEGORY_LOAD: "GET_PRODUCT_CATEGORY_LOAD",
   GET_PRODUCT_CATEGORY_SUCCESS: "GET_PRODUCT_CATEGORY_SUCCESS",
   GET_PRODUCT_CATEGORY_FAIL: "GET_PRODUCT_CATEGORY_FAIL",
   ///GET LATEST PRODUCT
   GET_LATEST_PRODUCT_LOAD: "GET_LATEST_PRODUCT_LOAD",
   GET_LATEST_PRODUCT_SUCCESS: "GET_LATEST_PRODUCT_SUCCESS",
   GET_LATEST_PRODUCT_FAIL: "GET_LATEST_PRODUCT_FAIL",
};

export default reduxConstants;
